### PR TITLE
Migrate contact emails

### LINKED ISSUE #296: Create migration for collection e-mail form
At present, the collection e-mail form (which is _data_ was manually created and saved in the snapshot present in jhu-idc/idc-isle-dc#92

While we do not have formal procedure for managing migrations (See #294), we should define this form as a migration in the `idcui` module so that it could be ingested via a `drush` command if need be.  Otherwise, the creation of this form would be an entirely manual process.  Creation of this form is a somewhat nuanced process.

### PR DESCRIPTION
**Pull request by jabrah**
Closes https://github.com/jhu-idc/iDC-general/issues/296

Adds a naive migration for the "contact email" entity, that is used to configure our collection and repository item contact forms in order to send emails to the expected addresses. These entities were already in our snapshot, but a migration and pre-defined data did not, so that if the entities were lost, or the system were started with a fresh database, they'd have to be recreated manually. 

There will be a CSV available in our `idc_ui_module/migrate` that can be used to recreate these entities

_Note that I did attempt to create the migration definition in `jhu-idc/idc_ui_module`, but I couldn't get the module to add the migration on install, so I just plopped the migration definition here._

### CODE REVIEW

**Comment by jabrah** [comment]
Presumably, this one test could be folded into an already existing test suite to cut down on `make resets` a bit. Would `10-migration-backend-tests` be the best place -- and if that's the case, would we need an accompanying verification test in Go, as opposed to simply checking for some known values in the UI, like is done now?

**Review by emetsger — APPROVED** [review]
Worked for me!

I could delete the entities provided by the snapshot, then run the test and have it pass.  Entities were re-created as expected.

**Comment by emetsger** [comment]
> Presumably, this one test could be folded into an already existing test suite to cut down on `make resets` a bit

I think the `end-to-end` folder is a good place for one-off tests that don't really require a test "suite", but I'm indifferent as to whether or not it is actually moved.

**Comment by emetsger** [comment]
I'm sorry that you couldn't get the migration to run on module install, but that can be done later.  I know the islandora module performs migrations on install, but maybe there's a little more magic to it besides adding a `migration` folder + csvs to your module.

**Pull request merged**
