### PR TITLE
End-to-end test experiment using testcafe

### PR DESCRIPTION
**Pull request by birkland**
# Overview
(This builds on #13, which adds a "static" Drupal build option, and github actions)

* Adds a `testcafe` service to docker-compose, which runs constantly in the background and can run tests on-demand. 
* Adds a `make test` target which will run tests
* Adds some simple tests in `end-to-end/tests` that are run by [testcafe](https://devexpress.github.io/testcafe/)

The `testcafe` service bind mounts the `end-to-end` directory, with tests present in `end-to-end/tests`.  `make test` will ultimately run a `docker-compose exec` that runs `npm test` inside the `testcafe` container.   If tests pass, `make` will terminate with a 0 error code.  If tests pass, you'll get a nonzero error code, and screenshots of failed tests will be dumped into a .gitignore'd `end-to-end/reports` directory.

Github actions are configured to run tests upon push.  If tests fail, the contents of `end-to-end/reports` will be attached to the build as an artifact.  

Although not necessary for tests to run via `make test`, It is worthwhile for developers to go `cd end-to-end`, and run `npm install --save-dev`, if they have Node and `npm` installed locally.  This will allow your IDE (e.g. vscode) to do autocomplete, show types (it's written in typescript!!)  and makes the development process much easier, in my opinion.   It is also possible to run tests locally by directly invoking `npm test` or testcafe, but I haven't tried it.  

# To Test 

## Local tests
* Checkout this pr, and do a `make reset` to start from a known starting point 
  * (or just start the environment manually via `docker-compose down -v`, `make docker-compose.yml`, `make up`.  It's important to build a new `docker-compose.yml` file if you do this manually)
* Do a `make up`
* Once up, do `make test`.  It should pass
* Look at the files in `end-to-end/tests`.  Edit one in order to make it fail.  For example, change one of the `.match` expectations to something bogus.  Run `make test` again and watch it fail.
  * look in `end-to-end/reports/screenshots` for screenshots of the page where tests fail

## Github actions
* Push this branch as a branch in your own personal git repo.   Navigate to your own personal git repo in the browser, and click on the "actions" tab.  You should see a build starting!  Wait for it to pass.
* Intentionally make a commit that fails, as you did before when locally.  Push this commit.  Watch the github action fail.  See if you can find the attached build artifact (it should be a zip file) and find the screenshot of the failed test. 

Resolves jhu-sheridan-libraries/idc-general#66

### CODE REVIEW

**Review by jaredgalanis — APPROVED** [review]
The one thought I have at the moment is that cross-browser support of testcafe is one of testcafe's more powerful features and we may want to consider testing against different browsers in the future (I think it is a-okay to leave it as only chromium for now).

I ran the tests as described in PR description (they worked), broke them as described (they broke), and also ran them off my local global installation of test cafe so that I could see the browser's UI (that worked).

That last piece was the main thing I wanted to make sure was possible with the configuration as is, since it can be very helpful for UI development and testing to verify what testcafe is seeing by looking at an actual browser.

That's a long'ish way of saying, looks good to me! 👍

**Comment by birkland** [comment]
Thanks @jaredgalanis !   With respect to netscape and/or other browsers, you or @jabrah can make that tweak when you're at the point of intentionally testing the UI with this framework.  I didn't do that in this PR, as my focus was on basic "is the site up" sort of tests.

Glad you could get the tests working locally too!  

I'll merge once the github actions PR is reviewed and merged.

**Comment by bseeger** [comment]
Do we, in general, want the tests to clean up after themselves?

**Comment by bseeger** [comment]
Just finished testing and it ran fine for me in all the scenarios you described above.  👍

**Review by bseeger — APPROVED** [review]

**Comment by birkland** [comment]
> 
> 
> Do we, in general, want the tests to clean up after themselves?

We can bring it up in the dev meeting, but at this point I'm fine with them leaving messes.  We'd conceivably need to clean up derivatives et al if we add binary content, roll back ingests, etc etc, which would seem to be a tall order at this stage. 

That being said, we _could_ have `make test` take a snapshot, run tests, then restore.  It would add a minute or so to the test cycle, but could be worth it.  If so, that's probably for another PR.

**Pull request merged**
