### PR TITLE
Update to use IDC's CSV plugin.

### LINKED ISSUE #376: Investigate how to get migrations to record error messages
At present, a bug or design flaw in the Drupal migration module results in error messages overwriting each other, leaving only a single (the latest) error message accessible.  Figure out a reasonable way to overcome this limitation.  

Some options on the table discussed at the last IDC planning meeting include:
* Adapting internal DiscoveryGarden code to IDC
* Create a module whose purpose is logging messages
* Add a hook that can intercept errors and log messages somehow

Assess the pros/cons/costs of these (or other) approaches so that we can make a decision as to whether to pursue any of them.

### PR DESCRIPTION
**Pull request by jordandukart**
Resolves jhu-idc/iDC-general#376

### CODE REVIEW

**Comment by jordandukart** [comment]
Depends on https://github.com/jhu-idc/idc_migration/pull/8.

**Comment by jordandukart** [comment]
Fixes https://github.com/jhu-idc/iDC-general/issues/376.

**Comment by bseeger** [comment]
@jordandukart - I integrated the module into this PR.  I'm going to write a quick test for it to see if we can see multiple errors.

**Comment by bseeger** [comment]
This PR now contains a small migration test that has 3 bad records in it (in 10-migration-backend-tests).  The migration is run and the message page is checked for 3 corresponding messages, one for each row. 

You could manually test this by running an ingest of items, each row containing a formatting error (missing semi-colon - this will NOT pickup missing required fields as validate is not turned on yet).  Then ensure that you see an error for each row on the messages page.

**Review by birkland — APPROVED** [review]
Looks great!

**Pull request merged**
