### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mjanowiecki**

### CODE REVIEW

**Comment by DonRichards** [comment]
I'm not ignoring this. I'm working on 2 issues ahead of this and this will likely need me to add tests to this PR as well.

**Review by jatjhu — APPROVED** [review]
Looks good to me! Thank you for adding those files.

**Comment by jatjhu** [comment]
> I'm not ignoring this. I'm working on 2 issues ahead of this and this will likely need me to add tests to this PR as well.

Oh, I did not see your comment. Will adding the files conflict with your changes? I want to use the files to add taxonomy.

**Comment by DonRichards** [comment]
It's unlikely.

**Pull request merged**
