### PR TITLE
Use the new field type.

### PR DESCRIPTION
**Pull request by jordandukart**

### CODE REVIEW

**Comment by jordandukart** [comment]
Fixes https://github.com/jhu-idc/iDC-general/issues/387.

**Comment by jordandukart** [comment]
Depends on https://github.com/jhu-idc/idc_defaults/pull/5 for the CI to pass I think.

**Comment by bseeger** [comment]
I merged the https://github.com/jhu-idc/idc_defaults/pull/5 PR.  To get the PR to run tests correctly, what needs to happen now is `composer update jhu-idc/idc_defaults` needs to be run to pull in the latest `idc_defaults` module hash into the composer.lock file.  Do you have time to do that @jordandukart?

**Comment by jordandukart** [comment]
Can do that sure.

**Review by bseeger — APPROVED** [review]
This looks good to me.

**Pull request merged**
