### PR TITLE
Collection Details page updates

### LINKED ISSUE #291: Implement "Ask the Collection Amin" functionality on Collection Details page
Clicking ask the collection admin opens a modal with an email form:

Use similar fields from the stand alone contact form, except fill out context information, such as collection names and type of question. 

*Need estimates*

### PR DESCRIPTION
**Pull request by jabrah**
Resolves https://github.com/jhu-idc/iDC-general/issues/291

## Note on "configuration" in this PR

There some configuration responsible for setting up the email to the collection contact email. It seems like this is not strictly considered "configuration" in Drupal, instead the plugin responsible for this saves it as a `contact_email` content entity. Because of this, it isn't exported to `config/sync` and is instead kept in the DB as content. If starting from a fresh DB, someone would need to set this configuration manually (unless we find a better way)

_Added @derekbelrose as a reviewer so ops is aware of this configuration note. We're asking about shifting responsibility of the config to a site admin _

## High level changes

* Change `collection_object.field_collection_contact_email` from plain text to Email field
* Show more metadata for collections
  * [x] TODO: Need to wait for https://github.com/jhu-idc/idc-ui-theme/pull/33 to be able to show the form
* Adds a new contact form: Collection Contact
  * Shown on all `/node/*` pages representing a Collection Object
  * Hidden by default, but shown in a modal when a user clicks the "Ask the collection admin" button"
    * Minor caveat: The contact form does not close automatically when the message is submitted. Instead it will clear the form and display a success/failure message. The user can click the X icon, or click outside the form to close it.

image

## Migrations

Because the data model was changed, this could _potentially_ result in migration changes. This data change from plain text to email field happens to be trivial, such that (I don't think) it does not effect migration behaviors -- noting that no validation is done currently during a migration. Because of this, all current migration tests should pass

## Testing

Once there is one or more collections created, navigate to the route for one of them (`/node/<col_id>`)

* You can click on the collection in the Content section of the admin toolbar
* You can click the "Library Collections" link on the home page, and you should be able to find the collection(s) listed

I don't think there's an email service in the dev stack (please correct me if I'm wrong), so the contact form will say that it failed to send the message. You can at least check the email attempt in the Drupal log in the Admin Toolbar `Reports > Recent log messages`. It will appear as an error with type: mail. The log should have a message similar to:

 `Message | Error sending email (from webmaster@localhost.com to moo.admin@example.com with reply-to moo.admin@example.com).
`

### CODE REVIEW

**Comment by jabrah** [comment]
There is a configuration that sets up an automated email sent to the email address in `collection_object.field_collection_contact_email` that is not captured in `config/sync`. It therefore needs to be maintained in the database in snapshots. This will be interesting when merging this and other PRs in the immediate future.

In the admin interface: Structure > Contact Forms > Collection Contact > Manage Emails > Override them with new contact emails. The config should be set similar to below - in this sample, Subject is set to `Feedback for [contact_message:field_collection:entity:title]: [contact_message:subject]`

image

**Comment by jabrah** [comment]
TODO:
* [x] Try to create a migration to introduce the contact emails config

**Comment by bseeger** [comment]
After I click send I see this where it says "Collection Object Collection B has been updated" - why does it say that? 

Screen Shot 2021-03-22 at 4 01 07 PM

(I can understand why it says the email didn't send, but the "object has been updated part is confusing".

**Comment by bseeger** [comment]
It is awesome to start to be able to navigate through collections, btw!

**Comment by jabrah** [comment]
@bseeger I haven't seen that message before. Mine usually look like:
image

This form should only read the collection admin email field from the collection. Do you know if anything was changed in your Collection B after this?

**Comment by bseeger** [comment]
Yeah - If I change a collection object, click save, go back to viewing the object and then try to send an email, once I click on "Send Message" is when I see the message. So it's just a slightly late drupal message.  Would this be picked up on the collection object page if it had a space for that?  I wonder why it shows up a few clicks later.

**Comment by bseeger** [comment]
I'm using firefox and don't get the checkbox part of the checkbox widget: 

Screen Shot 2021-03-22 at 4 46 27 PM

edit:  safari doesn't show it either.

**Comment by jabrah** [comment]
The entire form comes from a few different modules, so its mostly a black box for me. I'm assuming that the display that is saying "Collection Updated" is a left-over message from Drupal's default messaging mechanism

**Pull request merged**
