### PR TITLE
Use drupal/core-recommended for pinning down Drupal's dependencies

### PR DESCRIPTION
**Pull request by birkland**
This was based advice from @jordandukart as part of D9 audit, but isn't specifically required for compatibility with D9.  

From the [documentation](https://github.com/drupal/core-recommended):
> This project is for use with a Composer-managed Drupal site. It is recommended that all Composer-managed Drupal sites use this project.

> Require this project instead of the drupal/core subtree split in order to guarantee that all of the dependencies from drupal/core will be included in your Drupal site at exactly the same version that was tested with the version of Drupal you are currently using.

> The consequences of not using this project is that Drupal's dependencies may "float up" to more recent versions than were tested with Drupal when you use Composer to upgrade your Drupal site. Occasionally, new dependency versions introduce bugs in Drupal. While these sorts of errors are usually corrected fairly quickly, it can still be quite disruptive to be one of the first people encountering one of these bugs. Using the recommended dependencies avoids this problem by only using dependency versions that have already been tested with Drupal.

I noticed that there were quite a few dependency updates associated with this (where the advice from drupal/core-recommended conflicted with the lockfile), and most were downgrades.  Therefore, it looks like we were experiencing the "float up" problem described above.

Also note:  composer now creates a `modules` directory in `codebase/`.  I don't know the logic behind why that directory is suddenly appearing and being populated, but trust that it is part of some composer mechanism I'm not aware of, related somehow to the inclusion of drupal/core-recommended.

### CODE REVIEW

**Comment by jordandukart** [comment]
Passes my eye-test. In regards to that new directory being added is it to do with `drupal-custom-module` not having a mapping in [your](https://github.com/drupal/core-composer-scaffold#defining-project-locations) `core_composer_scaffolding` [configuration?](https://github.com/jhu-idc/idc-isle-dc/blob/development/codebase/composer.json#L175-L193)

**Comment by birkland** [comment]
> In regards to that new directory being added is it to do with `drupal-custom-module` not having a mapping in [your](https://github.com/drupal/core-composer-scaffold#defining-project-locations) `core_composer_scaffolding` [configuration?](https://github.com/jhu-idc/idc-isle-dc/blob/development/codebase/composer.json#L175-L193)

@jordandukart  Unfortunately, I'm not sure.  My understanding of composer is rather limited.  Is there some missing mapping that should have been present in `installer-paths`?  Essentially, this `composer.json` has its roots in the Born Digital drupal site used in ISLE development back in 2020, so this aspect hasn't occupied any of our mindshare.  _If there's a simple solution that is aligned with best practices, let me know and I can push some changes_.  As it stands, this PR is just passively reacting to what Composer is doing.. and I don't know if that is a good thing, or a bad thing.

**Comment by jordandukart** [comment]
Should be able to add that missing entry for `drupal-custom-module` in the scaffolding but definitely wouldn't be considered a blocker for this.

**Review by emetsger — APPROVED** [review]
Looks great. I heartily endorse this.

**Comment by emetsger** [comment]
I do have some problems when drupal starts:
```
drupal_1      | + composer install
drupal_1      | Gathering patches for root package.
drupal_1      | > DrupalProject\composer\ScriptHandler::checkComposerVersion
drupal_1      | Loading composer repositories with package information
drupal_1      | Installing dependencies (including require-dev) from lock file
drupal_1      | Package operations: 4 installs, 56 updates, 7 removals
drupal_1      |   - Removing psr/cache (1.0.1)
drupal_1      |   - Removing drupal/core-vendor-hardening (9.2.0)
drupal_1      |   - Removing doctrine/deprecations (v0.5.3)
drupal_1      |   - Removing symfony/contracts (v2.3.1)
drupal_1      |   - Removing doctrine/event-manager (1.1.1)
drupal_1      |   - Removing doctrine/persistence (1.3.8)
drupal_1      |   - Removing doctrine/reflection (1.2.2)
drupal_1      | Gathering patches for root package.
drupal_1      | Gathering patches for dependencies. This might take a minute.
drupal_1      |   - Installing drupal/core-project-message (8.9.16): Downloading (100%)         
drupal_1      |   - Downgrading symfony/polyfill-mbstring (v1.23.0 => v1.17.0): Downloading (100%)         
drupal_1      |   - Downgrading guzzlehttp/psr7 (1.8.2 => 1.6.1): Downloading (100%)         
drupal_1      |     Cleaning: guzzlehttp/psr7
drupal_1      |   - Downgrading guzzlehttp/promises (1.4.1 => v1.3.1): Downloading (100%)         
drupal_1      |     Cleaning: guzzlehttp/promises
drupal_1      |   - Downgrading symfony/polyfill-php72 (v1.23.0 => v1.17.0): Downloading (100%)         
drupal_1      |   - Downgrading symfony/polyfill-intl-idn (v1.23.0 => v1.17.0): Downloading (100%)         
drupal_1      |   - Downgrading guzzlehttp/guzzle (6.5.5 => 6.5.4): Downloading (100%)         
drupal_1      |   - Downgrading aws/aws-sdk-php (3.176.9 => 3.173.19):     Update failed (Could not delete /var/www/drupal/vendor/aws/aws-sdk-php/src: )
drupal_1      |     Would you like to try reinstalling the package instead [yes]? 
drupal_1      |                                                           
drupal_1      |   [Symfony\Component\Console\Exception\RuntimeException]  
drupal_1      |   Aborted                                                 
drupal_1      |                                                           
drupal_1      | 
drupal_1      | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
drupal_1      | 
drupal_1      | [cont-init.d] 99-custom-setup.sh: exited 1.
drupal_1      | [cont-finish.d] executing container finish scripts...
drupal_1      | [cont-finish.d] done.
```

I'm wondering if we need to make `composer install` non-interactive by supplying the `-n` switch.  However, the root cause of the issue is the inability to delete `vendor/aws/aws-sdk-php/src`, similar to the errors I encountered reviewing #152.  There's no reason why that directory can't be removed, permissions seem OK.

**Comment by birkland** [comment]
Interesting.  So the error you saw occurred when doing a `make up` over an existing codebase?   I think updating the buildkit image (separate from this issue) to add `-n` would be a good idea if that works.  

This doesn't appear to be an issue with `make reset`, or with creating a static image

**Comment by emetsger** [comment]
> Interesting. So the error you saw occurred when doing a `make up` over an existing codebase

Yup, exactly.  I did not perform a `make reset`.  Shouldn't be an issue as long as nothing is there to begin with.

**Pull request merged**
