### PR TITLE
UI tests

### PR DESCRIPTION
**Pull request by jabrah**
Tests should run automatically in CI. To run manually, in the base directory run the command `make test test=01-end-to-end`

* Adds several UI focused tests
* Adds / updates `end-to-end` test data
* Refactors the existing `end-to-end` tests to run (they weren't running in CI before)
* The assets image is brought up to be used along with some custom migrations

Recommend a squash merge

### CODE REVIEW

**Review by jaredgalanis — APPROVED** [review]
Seems good to me but I think you're now suffering from the same CI issues that Bethany was and I am on my PR.

**Comment by jabrah** [comment]
https://github.com/jhu-idc/idc-isle-dc/pull/204 should fix some failing tests, will rebase after it's merged to bring in those fixes -- will have to update test data as well

**Comment by jaredgalanis** [comment]
Yeah makes sense. I'm also waiting for it to come in.

**Comment by birkland** [comment]
#204 has just been merged!  🎉

**Review by emetsger — APPROVED** [review]
I think the PR needs rebasing and assuming everything passes, thumbs up from me!

**Comment by jabrah** [comment]
The PR should be up-to-date with the latest in `development` so it includes everything up to and including migrations validation. I ended up doing a merge commit instead of rebase, since the many rebases were becoming increasingly hairy

**Pull request merged**
