### PR TITLE
Update ui theme and module to add search widget in collections page

### PR DESCRIPTION
**Pull request by jabrah**
Relates to bug does not fully implement https://github.com/jhu-idc/iDC-general/issues/106. This PR creates the components described in the ticket, but limits its scope to only the list of (all) collections.

* Update references for UI code in `composer.lock` to point to latest commits
  * `jhu-idc/idc-ui-theme` commit 25615b020baf5b60fb21859c67d296106527f773
  * `jhu-idc/idc_ui_module` commit dbe5edee7434a4da824f7a84fb2c9404c2c8b900
* Remove a config file that was enabling Twig debugging by default

No configuration changes were made here, so I have not updated the snapshot.

### Changes:

* Adds new route `/collections`
* Changes the "Library Collections" card on the front page to navigate to the new collections route
* Adds "Featured Collections" block showing collections marked as "featured"
* Adds a search widget allowing users to search collections
  * User can enter arbitrary text to search. This text is treated as a solr query, so should allow for proximity search
  * Search results are paged with a user adjustable page size
  * User can change sort order and sort by parameters
  * Clicking on a search result will take you to the item's Drupal page (which is currently a placeholder)

There is no data by default in this PR. The page and search widget are rendered even if there is no data, but to check the searching behavior, you'll need to add some collection data.

### Notes and exceptions
* The current global search component in the top right of the header is a default Drupal component with an implementation separate from the newly added search component.
* If you edit an existing collection to check the "Featured Item" flag (featuring that collection), you may need to clear Drupal cache for it to appear in the "Featured Collections" component on the `/collections` page
* User search passes the text box search as a raw Solr query to allow users to use advanced features like proximity search. This may result in some unexpected behavior

image

### CODE REVIEW

**Comment by bseeger** [comment]
Hi John, 
I pulled down this branch and can get to the collection page as described.  This is what I'm seeing though:  

Screen Shot 2021-02-15 at 9 09 00 AM

**Comment by bseeger** [comment]
Also, I don't see any collections listed unless I'm logged in.

**Comment by bseeger** [comment]
I realize this is talking about number of collections, but on first glance it makes me think there are two pages of results: 
Screen Shot 2021-02-15 at 9 17 30 AM

**Comment by jabrah** [comment]
The strange text appearing below the collection titles is Drupal Twig debugging, perhaps set by a stray `codebase/web/sites/default/services.yml` file. This file was added by accident during the previous theme related PR, but should be deleted in this PR.

Good note about the page label, though. Maybe we should change to it "Showing 1 - 2 of 2 collections" or something to make it more clear

**Comment by jaredgalanis** [comment]
> The strange text appearing below the collection titles is Drupal Twig debugging, perhaps set by a stray `codebase/web/sites/default/services.yml` file. This file was added by accident during the previous theme related PR, but should be deleted in this PR.
> 
> Good note about the page label, though. Maybe we should change to it "Showing 1 - 2 of 2 collections" or something to make it more clear

yeah that makes sense to me about specifying what the number of things is that we're referring to.

**Comment by bseeger** [comment]
After I reset my code, it is working correctly now.  I had done something in git that was a flawed method. After a reset, I do see the collections listed correctly with no twig injected data.  I do see collections for a non-logged in user.  

One thing I'm noticing -- featured collection section does not seem to refresh when an object is changed from featured to not featured (and reverse). If I make a collection featured, it does not show up as featured right away in the featured collection section.  Likewise, if I remove it as a featured collection, it does not disappear.   I think there's some weird caching there.  I'm seeing this when both logged in and not.   (I'm using firefox and tried it in safari - both have issues.) Clearing cache will fix it, but any subsequent changes behave the same.

**Comment by bseeger** [comment]
Other than the above issue around caching, this looks good to me.

**Comment by jabrah** [comment]
@htpvu 

### Options

To expand on the search options menu, each option is presented with a dropdown

* Sort by
  * Relevance (default)
  * Title (alphabetical by collection title)
* Sort order
  * Ascending
  * Descending
* Items per page: 5, 10, 25, 50
* Current page: integers from 1 to max number of pages provided by search service

image

image

**Comment by jabrah** [comment]
@bseeger latest commit should address the Featured Items caching issue

**Review by htpvu — APPROVED** [review]
Reviewing the UI layout aspect of this PR: This looks good for me on the acknowledgement from @jaredgalanis that we'd make a change in the layout of search list options. The work to make that change is documented here https://github.com/jhu-idc/iDC-general/issues/289

**Review by bseeger — APPROVED** [review]
Looks great and works as expected now.

**Pull request merged**
