### PR TITLE
Config updates and fixes

### PR DESCRIPTION
**Pull request by bseeger**
This PR contains the following changes: 

1) changes Dates that were text strings to EDTF format
2) changes taxonomy terms that were content into being created by module installs (Language, Access Rights, Copyright and Use taxonomy terms). 
3) changes reference_value_pair widget to language_reference_pair widgets to be more clear in exactly what this widget does (ties a string to a language taxonomy term). 
4) changes the Opens Seadragon Display Mode to have more fields in it. Originally I didn't include all the fields because the UI would probably not be using this mode. Turns out that repository items that have Display Hint set to "Open Seadragon" will get their fields re-indexed and the search will then behave oddly.  I'm adding more fields to this mode as we will probably need them in the long run.  (or we might take this display mode out). 

To see the changes, you can: 
 - verify that all date fields on the Repository Item are EDTF fields. 
 - verify that there are no reference_value_fields on a Repository Item - they've been changed to language_value_fields. 
 - try to edit a language_value_field and note that you cannot change the taxonomy used (it is always set to "Language")
 
This PR addresses:  
 - https://github.com/jhu-idc/idc-isle-dc/issues/36
 - https://github.com/jhu-idc/idc-isle-dc/issues/41
 - https://github.com/jhu-idc/idc-isle-dc/issues/45

### CODE REVIEW

**Review by birkland — APPROVED** [review]
Works as advertised.

I did notice an error message in the logs when creating an item:
```
Notice: Undefined index: title in Drupal\update\ProjectSecurityRequirement::createFromProjectDataAndSecurityCoverageInfo() (line 103 of /var/www/drupal/web/core/modules/update/src/ProjectSecurityRequirement.php) 
```
I can't see an obvious connection with this PR, but I notice it only when creating an item with the stack from the PR.  I do not see it in `development`.  If you can reproduce it, feel free to merge this PR and file a bug fix.  I don't see any observable effects from this error.

**Comment by bseeger** [comment]
@birkland - interesting.  There's a drupal thread on this: https://www.drupal.org/project/drupal/issues/3132426. Sounds innocuous, overall.  I can still make a ticket, though, so we can keep an eye on it.

**Comment by emetsger** [comment]
> I did notice an error message in the logs when creating an item:
> 
> ```
> Notice: Undefined index: title in Drupal\update\ProjectSecurityRequirement::createFromProjectDataAndSecurityCoverageInfo() (line 103 of /var/www/drupal/web/core/modules/update/src/ProjectSecurityRequirement.php) 
> ```

For an additional datapoint, I do not see those errors in my log (after creating a repository object).

**Review by emetsger — APPROVED** [review]
Looks good to me!

**Pull request merged**
