### PR TITLE
Remove the "name" module configuraton

### LINKED ISSUE #22: Configuration import fails
If you do a `make config-import` , that fails because of failing to find the `name` module:
```
 [error]  Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization.
Unable to install the <em class="placeholder">name</em> module since it does not exist. in Drupal\Core\Config\ConfigImporter->validate() (line 755 of /var/www/drupal/web/core/lib/Drupal/Core/Config/ConfigImporter.php).

In ConfigImportCommands.php line 261:

  The import failed due to the following reasons:
  Unable to install the <em class="placeholder">name</em> module since it does not exist.
```

Digging deeper, this error has been happening all the time with the static/cloud drupal image, which would be really bad in production.  The fix for being able to detect such failures is in jhu-idc/idc-isle-buildkit#8 , which will cause Drupal to fail/exit if any initialization stages (such as syncing config) fails.  

Resolving this issue involves:
* incorporating the image tag from idc-isle-buildkit that contains the image startup fix
* fixing the issue with Drupal's config that is causing the above error

### PR DESCRIPTION
**Pull request by birkland**
* Removes the configuration for the `name` module, which was removed in an earlier commit
* Updates to the latest buildkit images to include a Drupal image that will terminate the container upon startup error
* Updates the snapshot to contain the updated config

# To test
* Verify github actions passes.  There's no point in running this PR locally
* Go to the tip of `development`, and specify in `.env` the value of `TAG` from this PR:  `upstream-20200824-f8d1e8e-14-g09641e3`.
* do `make static-docker-compose.yml` and `make up`.  You should encounter an error.  The reason:  the `drupal` image in `upstream-20200824-f8d1e8e-14-g09641e3` will now stop the container with an error code if the Drupal bootup sequence fails.  Drupal is happy in this PR because the configuration is fixed.  The tip of `development` does not have the fix, therefore ought to fail with a Drupal image that performs a check.

Tests for this functionality will be in a subsequent PR 

resolves #22

### CODE REVIEW

**Comment by emetsger** [comment]
I'm concerned about removing the `name` module.  Particularly because it defines the `field_person_preferred_name` field which has subfields such as: `title`, `first_name`, `last_name`, etc.  These are fields currently used in the Person taxonomy.  

If the fields in question are not being provided by another module in the interim, then the Person taxonomy will be broken in the sense that there won't be any place to store fundamental information about people.

I'll take a look at this PR and see if the actual consequences align with my hypothesis.  If so, I'd augment this PR to simply add the `name` module back in, rather than removing it from the configuration.

**Comment by birkland** [comment]
@emetsger I'm fairly certain that figuring out taxonomies and names is on @bseeger's  plate, rendering the current state of `development` with respect to content models and taxonomies somewhat irrelevant.  As it stands now, `name` was intentionally removed at one point, this PR is just focusing on making the configuration consistent, to remove a blocker for the S3 work.    That being said, I'm fine changing this PR to add back in the `name` module if you give the word after your research.  I don't have any position or interest in the high-level logical reasons for including or excluding it.

**Comment by emetsger** [comment]
Booting up this PR, and visiting the person taxonomy, you'll see that the fields are indeed missing as hypothesized.   However, per @bseeger  we aren't going to be using the name module, so I'll just test this as-is.

**Review by emetsger — APPROVED** [review]
Works as advertised.

One note, maybe to address in another PR, is that the external and active configuration do not seem to be synced.  After running `make config-export`, it seems that a SAML-related configuration block is missing from the external config:
```diff
diff --git a/codebase/config/sync/core.entity_form_display.user.user.default.yml b/codebase/config/sync/core.entity_form_display.user.user.default.yml
index 2ec2c837..3ab50ec2 100644
--- a/codebase/config/sync/core.entity_form_display.user.user.default.yml
+++ b/codebase/config/sync/core.entity_form_display.user.user.default.yml
@@ -24,6 +24,11 @@ content:
   language:
     weight: 0
     region: content
+  simplesamlphp_auth_user_enable:
+    weight: 0
+    settings: {  }
+    third_party_settings: {  }
+    region: content
   timezone:
     weight: 6
     region: content
```

**Comment by birkland** [comment]
A separate PR makes sense for the config update.

**Pull request merged**
