### PR TITLE
Use GitHub Container Registry for pulling images.

### PR DESCRIPTION
**Pull request by emetsger**
To test, execute the following, no errors should be encountered.
* `make -B docker-compose.yml`
* `docker-compose pull`

### CODE REVIEW

**Review by birkland — DISMISSED** [review]
It pulls great, but the Drupal image does not successfully start up:

```
drupal_1      | /var/run/s6/etc/cont-init.d/99-custom-setup.sh: line 36: return: block_content: numeric argument required
drupal_1      | [cont-init.d] 99-custom-setup.sh: exited 2.
```
Maybe one of the idc-specific customizations for that image is not working right?

**Comment by emetsger** [comment]
Yeah, there's a bum image pushed, which wouldn't be fixed in this PR

**Comment by birkland** [comment]
Is there a Drupal image fix PR imminent?  For the sake of the folks reviewing this I'd be hesitant to break things unless there is a fix coming shortly, or unless this PR was a blocker for a fix.  If so, then I'd be OK merging.

**Comment by emetsger** [comment]
yeah- i just pushed a new image, it should start

**Comment by birkland** [comment]
hm, Drupal container dies for a different reason now:

```
drupal_1      | +++ echo 'SELECT COUNT(DISTINCT table_name)
drupal_1      | FROM information_schema.columns
drupal_1      | WHERE table_schema = '\''drupal_default'\'';'
drupal_1      | +++ execute_sql_file_local /tmp/moo -- -N
drupal_1      | ++ local count=
drupal_1      | ++ return
drupal_1      | + local is_installed=0
drupal_1      | + '[' 0 -lt 1 ']'
drupal_1      | Drupal is not installed, no pre-existing state found.
drupal_1      | + echo 'Drupal is not installed, no pre-existing state found.'
drupal_1      | + exit 1
drupal_1      | [cont-init.d] 99-custom-setup.sh: exited 1.
```

This happens on `docker-compose up -d` no matter what, it seems a bootstrap isn't possible either.

**Comment by emetsger** [comment]
That should be fixed with https://github.com/jhu-sheridan-libraries/idc-isle-buildkit/pull/2/commits/9cc11e90e612e2fd987a1ddb4036d86e9ed79f7f

**Comment by emetsger** [comment]
Probably https://github.com/jhu-sheridan-libraries/idc-isle-buildkit/pull/2 should be merged first, then this PR can be reviewed without error (🤞)

**Comment by emetsger** [comment]
Actually:
# https://github.com/jhu-sheridan-libraries/idc-isle-dc/pull/6 should be merged (it's a requirement of https://github.com/jhu-sheridan-libraries/idc-isle-buildkit/pull/2)
# Then https://github.com/jhu-sheridan-libraries/idc-isle-buildkit/pull/2 should be able to be merged
# Then this PR (https://github.com/jhu-sheridan-libraries/idc-isle-dc/pull/5) should work.

**Comment by emetsger** [comment]
Sorry, these repositories are too intermingled for anyone's sanity.
1. https://github.com/jhu-sheridan-libraries/idc-isle-buildkit/pull/2 should be merged.  It will push a new (working) image.
2. Then merge https://github.com/jhu-sheridan-libraries/idc-isle-dc/pull/6
3. Then merge this PR, as it depends on https://github.com/jhu-sheridan-libraries/idc-isle-dc/pull/6

I think this should be the correct order.

**Review by birkland — APPROVED** [review]
OK, works great now!

**Pull request merged**
