### PR TITLE
Update migrations to use parse_entity_lookup plugin

### PR DESCRIPTION
**Pull request by emetsger**
## About
Updates migration definitions to use the `parse_entity_lookup` plugin.  ~~Note this will need to be rebased and merged after #120.~~  Given that there is other ongoing work around migration ids and export, this PR can wait if it will cause too much churn.

Fields updated (i.e., switch to use `parse_entity_lookup` plugin) are:
```
islandora_object field_contributor
islandora_object field_copyright_holder
islandora_object field_creator
islandora_object field_digital_publisher
islandora_object field_member_of
islandora_object field_publisher
islandora_object field_subject
corporatebody field_relationships
family field_relationships
persons field_relationships
```

## Testing

Nothing really to do, run `make test` and watch things pass.

### CODE REVIEW

**Review by bseeger — CHANGES_REQUESTED** [review]
Running tests now. 

Looks good, overall, for the repo item ingest.  The `member_of` field in the collection ingest needs to be adjusted as well, so it can take a collection_object or islandora_object.

**Comment by bseeger** [comment]
The Family and Corporate Body taxonomies both have a field (field_relationships) that can reference other taxonomy terms from multiple taxonomies and will need an update.

Also noticing that the `field_broader` on the geo location taxonomy has a `migration_lookup` call on it, but not sure why. It has no relationship with items or collections.  Don't know what the pseudo_id is or what purpose it serves - does it need to be there? 

The media migrations have a lot of `migration_lookup` calls as well that probably need to be replaced.  Maybe those were outside the scope of this PR, though.

**Comment by emetsger** [comment]
@bseeger 

> The `member_of` field in the collection ingest needs to be adjusted as well, so it can take a collection_object or islandora_object.

Are you referring to `field_member_of` in `migrate_plus.migration.idc_ingest_new_collection.yml` or in `migrate_plus.migration.idc_ingest_new_items.yml`?

If `migrate_plus.migration.idc_ingest_new_items.yml`, the `defaults` can only contain a single value (right now, `collection_object`), but the migration source spreadsheet can alter that if they wish to use `islandora_object`).  So an adjustment to the migration definition wouldn't be needed.

If `migrate_plus.migration.idc_ingest_new_collection.yml`, I think that'd be scoped for the work you're doing on identifiers (e.g. remove the `migration_lookup` and its usage once the identifiers are finished).

**Comment by emetsger** [comment]
~~@bseeger if you want I can just update this PR to do away with `migration_lookup` as well, wdyt?~~

With comments addressed and tests passing and my impending vacation, and with id refactoring not originally part of this PR, I'm suggesting that factoring out the `migration_lookup` plugin stay with the id refactoring work associated with export.

**Comment by emetsger** [comment]
@bseeger 

> Also noticing that the `field_broader` on the geo location taxonomy has a `migration_lookup` call on it, but not sure why. It has no relationship with items or collections. Don't know what the pseudo_id is or what purpose it serves - does it need to be there?

`field_broader` is one of the [problematic fields](https://github.com/jhu-idc/idc-isle-dc/tree/development/tests/10-migration-backend-tests#problematic-fields), and would be out of scope for this PR.  If I recall, we were going to "configure that problem away" by not using the `link` field type.

**Comment by bseeger** [comment]
@emetsger 

> field_broader is one of the problematic fields, and would be out of scope for this PR. If I recall, we were going to "configure that problem away" by not using the link field type.

Yeah - it's still a `Link`, just limited to external URL's  - that change is in the codebase already.  Should we make a separate ticket to update the migration for that (I'd agree that this change is outside of the scope of this PR)?

**Comment by bseeger** [comment]
@emetsger 

For: 
> With comments addressed and tests passing and my impending vacation, and with id refactoring not originally part of this PR, I'm suggesting that factoring out the migration_lookup plugin stay with the id refactoring work associated with export.

And
> If migrate_plus.migration.idc_ingest_new_collection.yml, I think that'd be scoped for the work you're doing on identifiers (e.g. remove the migration_lookup and its usage once the identifiers are finished).

That makes sense - I can work through those with the export stuff (and include the media migrations as well (where the migration_lookups are concerned) (?)).

**Review by bseeger — APPROVED** [review]

**Pull request merged**
