### PR TITLE
Repository object migration

### PR DESCRIPTION
**Pull request by emetsger**
Adds a Islandora Object migration test.
* This PR also makes minor changes to the Collection Object's migration definition, making it more robust.
* The list of problematic fields with respect to URIs is updated; this PR adds a number of them.

Test CSV is located in `tests/10-migration-backend-tests/testcafe/migrations/islandora_object.csv`
There are a number of related CSV files to import supporting objects, all prefixed with `islandora-object-*.csv` in the same directory.  This is so that the entities referenced by this test won't be impacted by entities from other tests; the entities in these CSV files ensures the Islandora Object migration is self-contained at the expense of maintaining skeleton CSV files.

Expected result is located in `tests/10-migration-backend-tests/verification/expected/item-01.json`

To review:
1. Run `make reset`
2. Run `tests/10-migration-backend-tests.sh`, observe tests pass.
3. Optionally, login to Drupal and navigate to the Content tab and select "Sample Repository Item" from the list.
4. There are a number of fields on Islandora Repository Objects (over 30), which I won't list here.  But you would expect to see a number of fields, many with multiple values, in multiple languages.

If you wish to break this test, you can make an edit to the expected result `tests/10-migration-backend-tests/verification/expected/item-01.json` and re-run `tests/10-migration-backend-tests.sh`.  The verification step should fail because the expected item data did not match the item for the data in Drupal.

### CODE REVIEW

**Comment by bseeger** [comment]
This looks good to me overall and the migration tests run successfully.  There are some minor changes needed to the tests:
 - Finding Aid -  you no longer need the help text and it's only a single value field (from a recent PR)
 - GeoPortal blacklight link also doesn't take a help text string anymore (from recent PR)
 - Library Catalog Link  also doesn't take a help text string anymore (from recent PR)

**Comment by emetsger** [comment]
> Finding Aid - you no longer need the help text and it's only a single value field (from a recent PR)
GeoPortal blacklight link also doesn't take a help text string anymore (from recent PR)
Library Catalog Link also doesn't take a help text string anymore (from recent PR)

Interestingly, tests pass despite this.  That is, the migration will succeed even for the fields that are not needed.  The data are migrated successfully (including multiple values and help text strings), and are present in the JSONAPI representation.

**Comment by emetsger** [comment]
@bseeger let me know if you'd like to review again- I updated the migration for those fields.  Otherwise I'll merge!

**Comment by bseeger** [comment]
Changes look good to me!  Not sure why the tests passed before - I suspect that drupal has a space to store that help text field regardless, and the toggle is just whether or not it gets displayed to the admin and is therefore editable.  I haven't confirmed this though.

**Pull request merged**
