### PR TITLE
SimpleSAML changes for IT@JH

### PR DESCRIPTION
**Pull request by jhujasonw**
Some simple changes to the config to test
SAML 2.0 with IT@JH

### CODE REVIEW

**Comment by jhujasonw** [comment]
I noticed this is failing its checks, I'm going to fire up a docker dev env and try to see if I can figure out the issue.

**Comment by emetsger** [comment]
@jhujasonw I made some updates to this PR which fixes the broken test.  Please take a look and give your thumbs up (or not!) and if all is well I'll merge.

**Comment by jhujasonw** [comment]
I will need to pull the branch and test this.  You added more changes to the remapping section of the config map.  I was keeping the remapping minimal because it previously worked in local dev docker and cloud test.  With the added remapping, I will want to test it in the cloud to make sure the added remapping doesn't interfere with any thing else that IT@JH may or may not be sending us.  I will try to get to this test in the next day or so.

**Comment by emetsger** [comment]
Yes additional mappings for required fields like mail and eduPersonPrincipleName were required, unfortunately.  The friendly name mappings are necessary on the Drupal side.  I added the remaining friendly names in case we needed them on the Drupal side.

**Comment by emetsger** [comment]
As an FYI @jhujasonw, I just pushed a test which should be included in this patch which verifies the expected attributes and their values from the local IdP.

**Review by jhujasonw — COMMENTED** [review]
Test in the cloud passed, this looks good to merge.

**Review by emetsger — APPROVED** [review]
After a dual review/ping-pong on this PR, things are ready for merging.

**Pull request merged**
