### PR TITLE
Metadata export and citations

### LINKED ISSUE #109: Implement item detail
Acceptance criteria:
- [x] Optionally display the about the item description if one exists (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
- [x] Display an oversized image of the item if it exists (addressed by jhu-idc/idc-isle-dc#135)
- [x] But if an image has the “hi-res” tag, then display its low-res derivative instead, and provide a link to download the hi-res image. (see https://github.com/jhu-idc/iDC-general/issues/315)
- [x] Unless hi-res image also have a restricted access tag, then provide link to send email to request the image (see https://github.com/jhu-idc/iDC-general/issues/305)
- [x] Display media player for item if it is relevant (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
Image viewer for images
Audio player for audio files
Video player for video files

- [x] List of all of the item's metadata: in order of Title, Description, Image, then the rest of the metadata (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
   - [x] display available language tags in visual tags (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
   - [x] display language tags in appropriate html tags to enable screenreader to process that tag. (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)
- [x] List item’s URI (aka its Citable URI) along with its metadata. (iDC-19) (addressed by https://github.com/jhu-idc/idc-isle-dc/pull/135)

Button group that when clicked:
- [x] Allows download of the item media via a link (see https://github.com/jhu-idc/iDC-general/issues/315)
- [x] If item’s image is marked as restricted access, provide link to send email request the image (iDC-15) (see https://github.com/jhu-idc/iDC-general/issues/305)
~~- [ ] Allows download of the whole digital object~~ this is captured by download media of the item and metadata export, so striking this requirement unless we determine otherwise
- [ ] Exports item metadata (see https://github.com/jhu-idc/iDC-general/issues/108)
- [ ] Opens a modal for displaying 3 styles of citation string for the item (see https://github.com/jhu-idc/iDC-general/issues/119)
- [x] Opens a modal with a form to ask questions about an item (see https://github.com/jhu-idc/iDC-general/issues/107)

### LINKED ISSUE #118: Implement ability to export search result metadata on Search Result page
extracted from https://github.com/jhu-sheridan-libraries/iDC-general/issues/111

Acceptance Criteria:
- [ ] Clicking “export search result’s metadata” will produce a CSV file of result’s metadata
- [ ]  ~~https://github.com/jhu-sheridan-libraries/iDC-general/issues/108 A modal popup allows users to select which metadata fields he/she wants to export for this result set.~~
- [ ]  Users are allowed to select between export the entire result set or export the current page of the result set
- [ ] Clicking "Export" will down load the desired CSV file to user's default location

### LINKED ISSUE #119: Implement to ability to export citation of individual item
extracted from https://github.com/jhu-sheridan-libraries/iDC-general/issues/111

Acceptance criteria 
- [ ]  Clicking “Download Bibliographic Information” will trigger a prompt asking user to choose between getting Bibliographic information for the **Current** page or for **the entire result set** 
- [ ] Once user makes the select, trigger the process to generate citation for selected items and download resulting file to user’s computer

### LINKED ISSUE #143: Search page needs to decode URL
This was found when working on metadata export.

When metadata export finishes, drupal redirects the user to the `/search` page with a set of query parameters. These parameters might include facet information.  The code that created the redirect URI has encoded the URI, so it ends up looking something like this:

`/search?query=zoo&f%5B0%5D=publisher%3AChicago%20Zoo`

The code that runs the `/search` page doesn't expect that the parameters will be encoded and doesn't notice the facet parameters.   The logic there needs to decode any parameters first before parsing so that it can handle any facets in the URI.

### PR DESCRIPTION
**Pull request by jaredgalanis**
Closes https://github.com/jhu-idc/iDC-general/issues/118 
Closes https://github.com/jhu-idc/iDC-general/issues/119
Closes https://github.com/jhu-idc/iDC-general/issues/109
Closes https://github.com/jhu-idc/idc-isle-dc/issues/143

This adds metadata export and citation features. 

To test metadata export go to all collections, collection detail, search, advanced search or item detail to export collections and items. Use the links in the search component and in the item detail cluster of buttons. Note the links operate on the type of resource they indicate. So using the export items link will only export items and vice-a-versa for the collections link.

To test citations go to item detail and click the citations button to open the citations modal. Note, the item will likely need creator / contributor field, Date Accessible, Digital Publisher to be populated for a valid citation to appear.

Screen Shot 2021-09-14 at 11 03 26 AM
Screen Shot 2021-09-14 at 11 03 48 AM

Screen Shot 2021-09-14 at 11 04 23 AM

Screen Shot 2021-09-10 at 1 32 30 PM
Screen Shot 2021-09-14 at 9 43 07 AM

### CODE REVIEW

**Comment by bseeger** [comment]
Test Plan: 
 - [x] all collections, 
    - [x] collections' metadata
    - [ ] ~~items' metadata~~ Not applicable
 - [ ] collection detail, 
    - [ ]  collection itself (?)
    - [x] items' metadata
 - [x] search,
    - [x] collections' metadata
    - [x] items' metadata
 - [x] advanced search or 
    - [x] collections' metadata
    - [x] items' metadata
 - [x] item detail
    - [x] metadata
    - [x] citations

**Comment by bseeger** [comment]
For the collection landing page: 

the link for "Export Collection Metadata"  is a little odd in that it includes "islandora_objects" in the ss_type search:  `https://islandora-idc.traefik.me/export_collections?query=itm_field_member_of:47%20AND%20(ss_type:collection_object%20OR%20ss_type:islandora_object)&nodeId=47`. It's innocuous, but maybe should be cleaned up.

**Comment by bseeger** [comment]
Actually, the link doesn't seem to work at all. If there are no sub collections, I only get an empty file.  How do I download the collection landing page's metadata itself?

**Comment by jabrah** [comment]
For collection details page, that seems like a bug / oversight. Since a collection can include other collections, we still need the `itm_field_member_of`, but we'll also need to append the query to include the collection itself

**Comment by bseeger** [comment]
Just confirming that if there are sub-collections in a collection - the link works just fine and probably as intended. 

Just a note: If there are multiple pages of items, all items are present in the export. (Namely, it's not limited by what page you're currently viewing)

**Comment by bseeger** [comment]
Note: if there are no results for a certain type in the results list (ie, not repository items), doing and export on that type will result in an empty csv file.  Innocuous, overall.

**Comment by bseeger** [comment]
This looks good overall and is functioning as expected.  I think it would be useful to include the collection as you describe here, @jabrah:  

> For collection details page, that seems like a bug / oversight. Since a collection can include other collections, we still need the itm_field_member_of, but we'll also need to append the query to include the collection itself

**Comment by bseeger** [comment]
For testing https://github.com/jhu-idc/idc-isle-dc/issues/143: 
I ran a search for something, added a few facets which trimmed the results, and clicked on the link to download items.   I was returned to the search and it still displayed the same results, with the proper facets enabled.

**Review by jabrah — APPROVED** [review]

**Review by bseeger — APPROVED** [review]
Looks good! Nice work!

**Pull request merged**
