### PR TITLE
Adds iDC content type configuration and first pass at Taxonomy configuration. 

### PR DESCRIPTION
**Pull request by bseeger**
This adds the Collection Content Type as well as makes the Repository Item Content Type match our application profile.  
This also adds in the taxonomies we plan to use, though I imaging these will change as I'm not sure they are fully setup right yet. 

- For both of the above content types, the Citable URL field will be populated when the object is saved. Right now you will have access to it because you are an admin user, but it is setup so that anything less then an admin cannot touch that field.  It is only created on the first save, so if you change it afterwards (as an admin) it should take your changes.
- The Repository Item Content Type field Model will not display "Collection" as an option anymore, thanks to use of a view that will filter it out. 
- This uses a new widget that is brought in via the reference_value pair repo.  It is a string field paired with an entity reference so we can tag with a term from a taxonomy, like Language.  It will need some consideration in the import work.
- The db has some initial taxonomy terms in it for Copyright and Access and Use. 

This does not have the mapping for the RDF in yet.  
This does not update the end-to-end/test work.  I will need some time to learn that framework to get the tests there back to function and to add a few more simple tests. 
This does not have solr configured yet for our data model.
This does not have the citation field in yet - as we haven't ironed out implementation details. 

Solves: 
- https://github.com/jhu-idc/iDC-general/issues/240
- https://github.com/jhu-idc/iDC-general/issues/245

Big step towards completing: 
- https://github.com/jhu-idc/iDC-general/issues/229

### CODE REVIEW

**Comment by bseeger** [comment]
And I just realized that I didn't remake the snapshot after rebasing off of development.  The biggest issue one might encounter is the name module.

**Comment by bseeger** [comment]
Re-took out 'name' module as my rebase accidentally added it back in.  Created and pushed new snapshot.

**Comment by birkland** [comment]
The CI failure here is new,   Filed bug #30 .  I'm pretty sure this happened because this PR was from a branch in this repo.  Interestingly, nobody has ever tried that before.

**Comment by birkland** [comment]
I can't comment on the substance of the content model changes, but everything I tried so far appeared to work:=
* `make config-import`
* created a collection
* created an item in the collection
  * Defined a 'subject' taxonomy term I could link to for the required 'subject' field
  * Used values from the new taxonomy terms defined as part of this work
  * verified that derivatives still work
  
Observations so far:
 * An interesting consequence of separating collection and media item is that it's no longer possible to associate an image or thumbnail with a collection. I don't know if this was ever a use case, but it something I did for the original demo quite a while back and just noticed isn't possible any more
 * I miss the "children" tab for collections.  User experience wise, I always tended to navigate to a collection, click on the "children" tab, click "add child" to add a member to a collection, rather than add an item then specify collection.  Not sure this is a problem per se, but it's a difference that stood out.

 Things I haven't tried or done yet:
   * Entering in a reference_value field (where/how would one do that?)
   * Looked through composer.lock
   
I'd like to finish the above, but so far it seems to work as advertised.

**Comment by bseeger** [comment]
Hi Aaron, some thoughts based on your comments. 

I'd like to get both those tabs you mention back on the collection content type, as we will need media on an object.  It was an over site that I forgot to mention that above.  I can create tickets for those later.  (they were not vital to the collection content type getting in). 

You can test the reference_value_pairs by filling in data for anything with a language select box near it - like description, abstract, alternative title - for either content type.  Those are reference_value_pairs.

**Comment by bseeger** [comment]
I should mention I usually work from a fork, but I was running out of patience with git the other night when I ran into a issue from my forked repo and figured that no one would care (yet) where this PR came from. 

So, I won't make it a standard practice to create a PR from a branch on this repo.  Though I'm glad it did help find a bug. :)

**Comment by emetsger** [comment]
These are my initial observations/comments, which may overlap with Aarons.  They aren't value judgments, just observations.

### Collection Type
* sub collections don't seem to be supported
* view to turn off the setting of citation url? 
  * Is this meant to be editable by the person creating the object
* collections don't use the islandora collection content model
* Reference value pairs elide the relationship between the value and the reference.  For example, “value” — rel:language —> taxonomy or “value” — rel:units —> taxonomy.  

### Taxonomy
The description text of the Person taxonomy seems nonsensical (from https://islandora-idc.traefik.me/admin/structure/taxonomy)

### Repository Resource
* "Collection" is available as a selection from resource type
* JHIR field and DSpace Identifier field are two different … types?  The DSpace ID allows linking to an existing Islandora resource whereas the JHIR field does not
* Subject field accepts terms from any taxonomy
* Like with Collection, the citation url is editable in the form.
* repository resources advertise islandora content models (i.e. still an islandora_object, and conform to a resource type/model)
* The `field_member_of` wasn't populated when I created a repo resource for a collection (at least, not the json view of the object - `?_format=json`)
* I think this is because there's not an "add child" - or whatever the label is - button for the collection

### Media
* Seem to behave as normal

**Comment by emetsger** [comment]
Dependency differences between the tip of `development` and this PR.  The only thing that seems potentially an issue is that `symphony-contracts` is downgraded; otherwise this just serves as documentation.

However, it is worth noting that we are now using IDC forks of `islandora_defaults` and `controlled_access_terms`.  

At some point in the future prior to going to production we'll need to discuss pinning the versions of the other `dev-*` branches.

(I'm considering make this output a CI action to accompany every PR)

```diff
diff --git a/deps.dev.21b2bd b/deps.d1ffccc9
index ec7ea2f7..01af654b 100644
--- a/deps.dev.21b2bd
+++ b/deps.d1ffccc9
@@ -64,7 +64,6 @@ drupal/file_replace                                       1.2.0
 drupal/filehash                                           1.4.0              
 drupal/flysystem                                          1.0.0              
 drupal/geolocation                                        3.2.0              
-drupal/hook_post_action                                   1.0.0              
 drupal/jwt                                                1.0.0-beta5        
 drupal/key                                                1.14.0             
 drupal/libraries                                          3.x-dev 3b7ae61    
@@ -80,7 +79,7 @@ drupal/restui                                             1.18.0
 drupal/search_api                                         1.18.0             
 drupal/search_api_solr                                    4.1.4              
 drupal/simplesamlphp_auth                                 3.2.0              
-drupal/token                                              1.7.0              
+drupal/token                                              1.8.0              
 drupal/transliterate_filenames                            1.4.0              
 drush/drush                                               9.7.2              
 easyrdf/easyrdf                                           0.9.1              
@@ -98,15 +97,16 @@ guzzlehttp/psr7                                           1.7.0
 instaclick/php-webdriver                                  1.4.7              
 islandora-rdm/islandora_fits                              dev-master 5eb0520 
 islandora/carapace                                        dev-8.x-3.x 551f5f4
-islandora/chullo                                          dev-dev bf14eca    
-islandora/controlled_access_terms                         dev-8.x-1.x f08a373
-islandora/crayfish-commons                                dev-dev d7c0044    
-islandora/islandora                                       dev-8.x-1.x 836d521
-islandora/islandora_defaults                              dev-8.x-1.x 68ebbfd
-islandora/jsonld                                          dev-8.x-1.x 976cfb9
-islandora/openseadragon                                   dev-8.x-1.x 6c9ae44
+islandora/chullo                                          dev-dev 6a5454e    
+islandora/crayfish-commons                                dev-dev f53e8da    
+islandora/islandora                                       dev-8.x-1.x 792b3d3
+islandora/jsonld                                          dev-8.x-1.x 36f6ca8
+islandora/openseadragon                                   dev-8.x-1.x 1401a03
 jcalderonzumba/gastonjs                                   v1.2.0             
 jcalderonzumba/mink-phantomjs-driver                      v0.3.3             
+jhu-idc/controlled_access_terms                           dev-8.x-1.x 641bc66
+jhu-idc/islandora_defaults                                dev-8.x-1.x ad6592c
+jhu-idc/reference_value_pair                              dev-main 0a75d20   
 justinrainbow/json-schema                                 5.2.10             
 laminas/laminas-diactoros                                 1.8.7p2            
 laminas/laminas-escaper                                   2.6.1              
@@ -122,7 +122,7 @@ masterminds/html5                                         2.7.3
 mikey179/vfsstream                                        v1.6.8             
 ml/iri                                                    1.1.4              
 ml/json-ld                                                1.2.0              
-monolog/monolog                                           1.25.5             
+monolog/monolog                                           1.26.0             
 myclabs/deep-copy                                         1.10.1             
 myclabs/php-enum                                          1.7.6              
 namshi/jose                                               7.2.3              
@@ -146,7 +146,7 @@ phpunit/php-text-template                                 1.2.1
 phpunit/php-timer                                         2.1.2              
 phpunit/php-token-stream                                  3.1.1              
 phpunit/phpunit                                           7.5.20             
-pimple/pimple                                             v3.3.0             
+pimple/pimple                                             v3.3.1             
 psr/cache                                                 1.0.1              
 psr/container                                             1.0.0              
 psr/event-dispatcher                                      1.0.0              
@@ -170,7 +170,7 @@ sebastian/resource-operations                             2.0.1
 sebastian/version                                         2.0.1              
 seld/jsonlint                                             1.8.0              
 seld/phar-utils                                           1.1.1              
-sibyx/phpgpx                                              1.0-RC5            
+sibyx/phpgpx                                              1.0.1              
 silex/silex                                               v2.2.4             
 simplesamlphp/composer-module-installer                   v1.1.6             
 simplesamlphp/saml2                                       v4.1.7             
@@ -214,17 +214,18 @@ symfony/browser-kit                                       v3.4.43
 symfony/class-loader                                      v3.4.43            
 symfony/config                                            v3.4.43            
 symfony/console                                           v3.4.43            
-symfony/contracts                                         v2.3.1             
+symfony/contracts                                         v2.0.1             
 symfony/css-selector                                      v3.4.43            
-symfony/debug                                             v3.4.46            
+symfony/debug                                             v3.4.47            
 symfony/dependency-injection                              v3.4.43            
+symfony/deprecation-contracts                             v2.2.0             
 symfony/dom-crawler                                       v3.4.43            
-symfony/event-dispatcher                                  v3.4.46            
+symfony/event-dispatcher                                  v3.4.47            
 symfony/filesystem                                        v3.4.43            
 symfony/finder                                            v3.4.43            
-symfony/http-foundation                                   v3.4.46            
-symfony/http-kernel                                       v3.4.46            
-symfony/inflector                                         v5.1.8             
+symfony/http-foundation                                   v3.4.47            
+symfony/http-kernel                                       v3.4.47            
+symfony/inflector                                         v5.2.0             
 symfony/lock                                              v3.4.43            
 symfony/phpunit-bridge                                    v3.4.43            
 symfony/polyfill-ctype                                    v1.20.0            
@@ -238,16 +239,16 @@ symfony/polyfill-php70                                    v1.20.0
 symfony/polyfill-php72                                    v1.20.0            
 symfony/polyfill-php80                                    v1.20.0            
 symfony/process                                           v3.4.43            
-symfony/property-access                                   v4.4.16            
+symfony/property-access                                   v4.4.17            
 symfony/psr-http-message-bridge                           v1.2.0             
-symfony/routing                                           v3.4.46            
-symfony/security                                          v3.4.46            
+symfony/routing                                           v3.4.47            
+symfony/security                                          v3.4.47            
 symfony/serializer                                        v3.4.43            
-symfony/string                                            v5.1.8             
+symfony/string                                            v5.2.0             
 symfony/translation                                       v3.4.43            
 symfony/validator                                         v3.4.43            
 symfony/var-dumper                                        v4.4.11            
-symfony/yaml                                              v3.4.46            
+symfony/yaml                                              v3.4.47            
 theseer/tokenizer                                         1.2.0              
 twig/extensions                                           v1.5.4             
 twig/twig                                                 v1.43.0
```

**Comment by bseeger** [comment]
Addressing @emetsger comments: 

For sub collections -- you're right! I forgot to put a member_of field on the collection object. I will fix that and push a change to it. 

For the citable URL — if you’re logged in as an admin in the system right now you can edit it. But users who login as Collection Admin and Global Admin will not be able to (unless we let them).  So the fact that you can edit them now is a side effect of not having roles yet.  (The permissions on that field are limited in the content type's field_citable_url setup, so you can see the setup if you'd like.)

For collections not using the islandora collection content model  - yeah, this is on purpose. I'm not sure we need to have that set, as it's used to differentiate a repository item from a collection.  And the way _we_ have of doing that is by checking the content type.  If there is something upstream that seems to need it, I'm happy to put that in, but I don't _think_ we need it right now.  

For person taxonomy - good catch. I need to fix these as I hit a field limit and Michelle gave me shorter descriptions. Will update soon. 

Repository Item
- I'll take out "collection" from that list for resource type
- Subject is limited to about 5 different taxonomies (Person, Corporate Body, Family, Subject and Geographic Field).  Were the ones you were entering in those? 
- JHIR and Dspace id --  I'll fix this - they should both be external links and one might not be 
- Citable URl - same deal  as above, it's a role thing.  
- I missed adding field_member_of to the collection content type, which is why you can't put a collection as a member of another collection. I'll fix this soon.

**Comment by birkland** [comment]
I took a look at the last remaining items last night.  I'm inclined to approve at this point just to get a majority of the work in, with known issues and TODOS.  However, @bseeger can you clarify which issues you intend to resolve in subsequent commits to this PR, and which ones will be dealth with later?

**Review by emetsger — APPROVED** [review]
My understanding is that @bseeger is planning to fix a couple of minor things on the PR, but as far as I'm concerned we're good to merge after that!

**Comment by bseeger** [comment]
I updated the branch with some fixes: 

- adds member_of to collection_object
- fixes descriptions on taxonomy vocabularies
- adds RDF mapping for repository item and collection object
- adds language field for the title on a repository item and collection object (since there is no other way to indicate language for title - we can't change that field to a reference_value_pair)
- JHIR and DSpace Identifier fields are both now links to external urls
- filters "Collection" from Resource Type list in the repository item field 

Created tickets for a few things that need to be fixed/added: 
- https://github.com/jhu-idc/idc-isle-dc/issues/36
- https://github.com/jhu-idc/idc-isle-dc/issues/35

**Review by birkland — APPROVED** [review]
Let's merge this in!

I noticed an issue with RDF, if you can confirm it, let's just file a ticket.  I created "abstract" content in two languages.  The jsonld linked to language URIs, but did not include any of the text content.  See for example:

image

image

**Comment by bseeger** [comment]
Thanks, @birkland  - that's an known issue and I created a ticket for it: https://github.com/jhu-idc/idc-isle-dc/issues/37.

**Pull request merged**
